name: 'Circumventures, LLC'
favicon: null
layout_spectrum: 0.08490944071672857
typography_spectrum: 0.5819964460097253
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8653981264214963
  lightness: 0.6282831195276231
  saturation: 0.33758366224355996
  rhythmicContrast: 0.578510751016438
purpose: []
