name: 'Circumventures, LLC'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#122632'
    - '#fff8dd'
    - '#fcb040'
    - '#bf8c3c'
    - '#c1c1b0'
  brandStrength: 0.8125
  lightness: 0.6282831195276231
  saturation: 0.33758366224355996
  rhythmicContrast: 0.578510751016438
purpose: []
